# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:

    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Start server
      run: npm start
      
    - name: Run API tests
      run: npm test
